# Generated by Django 5.0.2 on 2024-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_description', models.TextField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
