# Generated by Django 5.0.2 on 2024-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Employee',
        ),
    ]
