# Generated by Django 5.0.2 on 2024-03-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_team_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
    ]
