# Generated by Django 5.0.2 on 2024-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_employee_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task',
        ),
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.ManyToManyField(to='team.task'),
        ),
    ]
