# Generated by Django 5.0.2 on 2024-03-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_task_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='task',
            new_name='employee_task',
        ),
    ]
