# Generated by Django 5.0.2 on 2024-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_task_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_employee',
            field=models.ManyToManyField(to='team.employee'),
        ),
    ]
