# Generated by Django 5.0.2 on 2024-03-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_remove_task_task_employee_employee_employee_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_task',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
    ]
